### ISSUE TITLE
Use V2 API

### ISSUE THREAD

**Issue by NiklasMerz** [NiklasMerz/netlify-analytics-collector#9]
Looks like the Analytics site now uses a V2 API and we get errors with V1

**Comment by danurbanowicz** [comment]
What a shame! Not sure if you saw Netlify's post on the V1 deprecation schedule:-

https://answers.netlify.com/t/analytics-v1-api-deprecation/46760

**Comment by NiklasMerz** [comment]
Damn. Thank your for this information. I did not see it yet just had a failed request recently.

We need to switch to v2 quickly. Any help welcome! 

/cc @DavidM42

**Comment by NiklasMerz** [comment]
Looks like the V2 has the exact same data structure as V1. I will release a new version of this action tomorrow.
